// <auto-generated />
namespace MuzON.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addedreferencetoplaylistincomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedreferencetoplaylistincomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201810260740421_Added-reference-to-playlist-in-comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
